# Generated by Django 3.0.4 on 2020-04-06 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_recsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerproduct',
            options={'ordering': ['banner_id']},
        ),
        migrations.AlterModelOptions(
            name='productinteractions',
            options={'ordering': ['timestamp', 'user_id']},
        ),
        migrations.AlterField(
            model_name='bannerproduct',
            name='product_id',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
