# Generated by Django 3.0.4 on 2020-04-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_recsys', '0002_auto_20200406_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_id', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
